### ISSUE TITLE
Good Work～

### ISSUE THREAD

**Issue by BlueBlueFF** [yfzhang114/LLaVA-Align#1]
How to get token prob like fig.4? use which tools?

**Comment by yfzhang114** [comment]
Firstly, we obtained the attention map generated by our model. 
Next, we segmented the attention map into sections corresponding to text and image tokens. This segmentation allowed us to focus specifically on the attention patterns between tokens related to text and those related to images.
Lastly, we utilized the Matplotlib library in Python to both visualize and annotate these attention patterns. Specifically, the plt.text function within Matplotlib facilitated the addition of textual annotations to our heatmap-like representation,
