### ISSUE TITLE
 use_calibrate = model_kwargs.get("use_calibrate", False)在设置为true时出现错误

### ISSUE THREAD

**Issue by veinhao** [yfzhang114/LLaVA-Align#2]
在vcd_utils/vcd_sample.py里，当设置use_calibrate为true时，程序不能正常运行：cuda error:device-side assert triggered，这一句是矫正模型时必需的吗？

**Comment by veinhao** [comment]
上面的情况在运行experiments/eval/calibrate/llava_calibrate.py时出现

**Comment by yfzhang114** [comment]
can you attach the full error log?
which experiment are you reproduing?

**Comment by yfzhang114** [comment]
``use_calibrate`` is not required for our experiments, and we have commented out that part of the code. Thank you for letting me know. If you have any further questions or need assistance with anything else, feel free to ask!

**Comment by veinhao** [comment]
谢谢，明白了



---原始邮件---
发件人: "Yi-Fan ***@***.***&gt;
发送时间: 2024年3月28日(周四) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yfzhang114/LLaVA-Align]  use_calibrate = model_kwargs.get("use_calibrate", False)在设置为true时出现错误 (Issue #2)




 
use_calibrate is not required for our experiments, and we have commented out that part of the code. Thank you for letting me know. If you have any further questions or need assistance with anything else, feel free to ask!
