### ISSUE TITLE
二分类POPE数据集校验：eval_pope_calibrate.py，args.gen_files似乎没有提供

### ISSUE THREAD

**Issue by veinhao** [yfzhang114/LLaVA-Align#3]
你好，我在复现论文中二分类POPE数据集的实验效果时（eval_pope_calibrate.py），无法得到args.gen_files对应的输入文件，它是通过哪一个文件里的代码提供的吗？我无法找到是哪一个文件生成的输出结果，能麻烦你提供一下吗？

**Comment by yfzhang114** [comment]
gen_files 就是你本身输出的结果与--answers-file对应比如如果运行下面的code

```python
python ./eval/llava_naive.py \
--model-path ${model_path} \
--question-file ./data/POPE/${dataset_name}/${dataset_name}_pope_${type}.json \
--image-folder ${image_folder} \
--answers-file ./output/llava15_${dataset_name}_pope_${type}_7b_seed${seed}.jsonl \
--noise_step $noise_step \
--seed $seed
```
那你的gen_files 应该设置为 ./output/llava15_${dataset_name}_pope_${type}_7b_seed${seed}.jsonl

**Comment by veinhao** [comment]
谢谢你的回复，我尝试按照你的提示修改后仍然无法运行：
在你提供的llava_naive.py中似乎没有写入['naive', 'none', 'unk', 'none_unk']这几个键的过程，然而eval_pope_calibrate.py中需要args.gen_files对应文件的['naive', 'none', 'unk', 'none_unk']，如果没有那么下面的W，b也无法确定

**Comment by yfzhang114** [comment]
experiments/scripts/pope/run_llava.sh 
这里才是calibrate需要运行的命令，naive是baseline的

**Comment by veinhao** [comment]
谢谢，明白了
